name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: install
        working-directory: ${{ env.working-directory }}
        run: npm ci
      - name: Build
        working-directory: ${{ env.working-directory }}
        run: npm run build
      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          entryPoint: ${{ env.working-directory }}
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
